import type { Metadata } from "next";
import Provider from "./utilities/provider";
import Navbar from "./navbar/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
